fix regex

diff --git a/templates/default/dockerImageDelete.sh.erb b/templates/default/dockerImageDelete.sh.erb
--- a/templates/default/dockerImageDelete.sh.erb
+++ b/templates/default/dockerImageDelete.sh.erb
@@ -9,18 +9,17 @@ help() {
     exit 1
 }
 
-VALID_IMAGE_NAME='<%= node['hopsworks']['docker']['image-validation-regex'] %>'
-
+VALID_IMAGE_NAME='^([a-z0-9]+(-[a-z0-9]+)*.)*[a-z0-9]+(:[0-9]*)?/[-:._a-zA-Z0-9]{0,62}[-:.a-zA-Z0-9]$'
 # Sanity checks for injection attacks
 if ! [[ $2 =~ $VALID_IMAGE_NAME ]] ; then
-  echo "error: Not an image name $3" >&2
+echo "error: Not an image name $3" >&2
 	help
-fi
+    fi
 
-if [[ "$(docker images -q $2 2> /dev/null)" == "" ]]; then
+    if [[ "$(docker images -q $2 2> /dev/null)" == "" ]]; then
 	exit 0
-else
-  docker rmi -f $2
-fi
+    else
+	docker rmi -f $2
+   fi
 
 exit $?
